import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import fetch from 'node-fetch'
import useSWR from 'swr'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>welcome to abegy-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my Example App
        </h1>

        <p className={styles.description}>
          Manually search the label intel in the <a href="http://localhost:3000/api/test">AltRestAPI</a>
        </p>
        <div>
    </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
